require 'win-ffi/user32'

module WinFFI
  module User32
    CREATEPROCESS_MANIFEST_RESOURCE_ID  = 1
    ISOLATIONAWARE_MANIFEST_RESOURCE_ID = 2
    ISOLATIONAWARE_NOSTATICIMPORT_MANIFEST_RESOURCE_ID = 3
    MINIMUM_RESERVED_MANIFEST_RESOURCE_ID = 1
    MAXIMUM_RESERVED_MANIFEST_RESOURCE_ID = 16

    RT_MANIFEST = 24
  end
end