module WinFFI
  module User32
    CREATEPROCESS_MANIFEST_RESOURCE_ID  = 1
    ISOLATIONAWARE_MANIFEST_RESOURCE_ID = 2
    ISOLATIONAWARE_NOSTATICIMPORT_MANIFEST_RESOURCE_ID = 3
    MINIMUM_RESERVED_MANIFEST_RESOURCE_ID = 1
    MAXIMUM_RESERVED_MANIFEST_RESOURCE_ID = 16
    if WINDOWS_VERSION >= 8
      MAX_LOGICALDPIOVERRIDE = 2
      MIN_LOGICALDPIOVERRIDE = -2
    end
  end
end